version: '3.8'

services:
  backend:
    build: .
    container_name: quiz-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/dev.db
    env_file:
      - .env
    volumes:
      - sqlite_data:/app/data

volumes:
  sqlite_data: